### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by elbowdonkey** [OpenXbox/xbox-client-xamarin#25]
I saw that there's a WIP branch called `gtk_desktop` which adds xnano.GtkDesktop. I'm wondering if you were ever able to get this to work.

I tried building it and had to adjust `ConsoleListPageViewModel.cs` to use this:

```
var offlineDevice = new SmartGlass.Device(currentDev.DeviceType, currentDev.Address, currentDev.Name, currentDev.LiveId, currentDev.HardwareId);
```

That allows it to compile and run on macOS, but not much more. When clicking "Authenticate" the app quits. When clicking "Skip", the app just sits.

I haven't dug into why (I'm not too familiar with C# based apps). I figured before diving in, I'd get a feel for where things are direct from the author.

**Comment by varun-dhar** [comment]
Why don't you just use the [Nano client](https://github.com/OpenXbox/xbox-smartglass-nano-python)? You can install it with pip, and it works on all platforms as long as python is installed.

**Comment by elbowdonkey** [comment]
Thanks for pointing it out. I wasn't aware that worked.

Though, after having tried it, it segfaults after finding a console. I'll investigate and post an issue on that repo if needed.
